item {
  id: 1
  name: 'chair'
}

item {
  id: 2
  name: 'stove'
}

item {
  id: 3
  name: 'stool'
}

item {
  id: 4
  name: 'oven'
}

item {
  id: 5
  name: 'sofa'
}

item {
  id: 6
  name: 'ladder'
}
