# run from happy-walrus root: docker run -it -p 8888:8888 --name final_project -v $pwd/../:/tensorbin --rm final_project
FROM tensorflow/tensorflow:latest-py3

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt-get update && apt-get install -y protobuf-compiler python-pil python-lxml python-tk
RUN pip3 install --upgrade pip
RUN pip3 install --user Cython
RUN pip3 install --user contextlib2
RUN pip3 install --user jupyter
RUN pip3 install --user matplotlib

RUN mkdir /tensorbin
RUN apt-get install -y git
RUN git clone https://github.com/tensorflow/models.git
RUN git clone https://github.com/cocodataset/cocoapi.git
#RUN cd cocoapi/PythonAPI
#RUN make
#RUN cp -r pycocotools /models/research/

#RUN cd /models/research
#RUN protoc object_detection/protos/*.proto --python_out=.
#RUN export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
#RUN cd /
#~/.local/bin/jupyter-notebook --ip=0.0.0.0 --allow-root
