item{
	id: 1
	name: 'cabinet'
}
item{
	id: 2
	name: 'chair'
}
item{
	id: 3
	name: 'countertop'
}
item{
	id: 4
	name: 'dishwasher'
}
item{
	id: 5
	name: 'outlet'
}
item{
	id: 6
	name: 'oven'
}
item{
	id: 7
	name: 'sofa'
}
item{
	id: 8
	name: 'stool'
}
item{
	id: 9
	name: 'stove'
}
item{
	id: 10
	name: 'utensil'
}